### ISSUE TITLE
Shader Screenshots of biomes

### ISSUE THREAD

**Issue by DestinyTheGreat** [Sancires/Santopia#1]
![2021-07-08_15 02 29](https://user-images.githubusercontent.com/65428450/124997086-eadd7000-dffe-11eb-92e4-eb7880c6b93b.png)
![2021-07-08_15 04 49](https://user-images.githubusercontent.com/65428450/124997142-ffba0380-dffe-11eb-9cae-3d0bdf8d9141.png)
![2021-07-08_15 07 39](https://user-images.githubusercontent.com/65428450/124997180-0779a800-dfff-11eb-8863-851029ba2a6d.png)

Shaders used: Chocapic v6 Medium preset and Sildurs Vibrant with custom settings
Resource pack: Lithos 32x

Let me know if these are not satisfactory and/or you need more

**Comment by Sancires** [comment]
These are all great, thank you!
